services:

    # CI HUB Configuration Loader
    CIHub\Bundle\PimcoreCIHubAdapterBundle\Loader\PimcoreCIHubConfigurationLoader:
        tags:
            - { name: 'pimcore.datahub.configuration.loader' }
